name: Renovate
on:
  schedule:
    - cron: '0 3 * * 3'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.0.1
        with:
          configurationFile: .github/workflows/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
